from __future__ import annotations

try:
    # Generated by setuptools-scm at build time (see [tool.setuptools_scm] in pyproject.toml).
    from hadolint_py._version import __version__
except ImportError:  # running from a source checkout without building first
    __version__ = '0.0.0'

__all__ = ['__version__']
